[workspace]
members = [
  "active-sequences",
  "csv-partition",
  "expand-urs",
  "ftp-export",
  "json2fasta",
  "kv",
  "pubs",
  "rnc-core",
  "rnc-utils",
  "rnc-test-utils",
  "shuffle-json-sequences",
  "split-sequences",
  # "jseq",
]
