[workspace]
members = [
  "json2fasta",
  "split-sequences",
  "csv-partition",
  "ftp-export",
  "pubs",
  "shuffle-json-sequences",
  "kv",
  # "jseq",
  "active-sequences",
  "rnc-core",
  "rnc-utils",
]
